server:
  port: 1905

app:
  version: 1.0.16  # App Version
  version-file-path: /root/projects/wowdiscordbot/version.txt
  discord:
    webhook-url: "${PROD_DISCORD_WEBHOOK_URL}"

wow-api:
  username: "${PROD_WOW_API_USERNAME}"
  password: "${PROD_WOW_API_PASSWORD}"

discord:
  api:
    url: https://discord.com/api/v10
  bot:
    token: "${PROD_DISCORD_BOT_TOKEN}"
  client:
    id: "${PROD_DISCORD_CLIENT_ID}"
    secret: "${PROD_DISCORD_CLIENT_SECRET}"
  redirect:
    uriCallback: "${PROD_DISCORD_CALLBACK_URL}"
    uriInvite: "${PROD_DISCORD_INVITE_URL}"

spring:
  datasource:
    url: "${PROD_DB_URL}"
    username: "${PROD_DB_USERNAME}"
    password: "${PROD_DB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    clean-disabled: true

jwt:
  secret: "${PROD_JWT_SECRET}"
  expiration: 86400000  # 24 hours in milliseconds

logging:
  file:
    name: /root/projects/wowdiscordbot/logs/azerite-bot.log
    max-size: 10MB
    max-history: 7
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
