server:
  port: 1905


wow-api:
  username: pyro
  password: pyro


discord:
  bot:
    token: MTI2MTM0NDU4OTYwOTE3MzA0Mg.GOYY-o.8D2BEslm7ixYMeHvy2kCdEaUUcSfy5hSY2lTkM

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wowdiscordbot
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: true
    clean-disabled: true