name: Deploy to VPS

on:
  push:
    branches:
      - main  # Sadece 'main' dalına yapılan push'larda çalışır.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu Checkout Et
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 11'i tamamen kaldır
      - name: Remove existing Java version
        run: |
          sudo apt-get remove --purge openjdk-11-*
          sudo apt-get autoremove --purge
          sudo apt-get clean
          java -version