name: Deploy to VPS

on:
  push:
    branches:
      - main  # Sadece 'main' dalına yapılan push'larda çalışır.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu Checkout Et
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Mevcut Java sürümlerini temizle
      - name: Clean up existing Java versions
        run: |
          sudo apt-get remove --purge -y openjdk-11-* openjdk-8-* temurin-*
          sudo apt-get autoremove -y

      # 3. Java 17'yi kur
      - name: Install OpenJDK 17
        run: |
          # Java 17'yi yükle
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      # 4. JAVA_HOME çevre değişkenini Java 17 olarak ayarla
      - name: Set JAVA_HOME to Java 17
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

      # 5. Varsayılan olarak Java 17'yi ayarla
      - name: Set Java 17 as default
        run: |
          # Varsayılan Java 17'yi ayarla
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1711
          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1711
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

      # 6. Java sürümünü doğrula
      - name: Verify Java version
        run: |
          java -version

      # 7. Gradle'ı kur ve build işlemi yap
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v2
        with:
          gradle-version: '8.0.1'  # İhtiyacınıza göre Gradle versiyonunu seçebilirsiniz

      # 8. Gradle wrapper dosyasına çalıştırılabilir izin ver
      - name: Give execute permissions to gradlew
        run: chmod +x ./gradlew

      # 9. Gradle ile build al
      - name: Build with Gradle
        run: ./gradlew clean build  # Bu komut ile .jar dosyasını build ediyoruz

      # 10. SSH Kurulumu
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${VPS_IP} >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking=no" >> ~/.ssh/config

      # 11. .jar dosyasını VPS'ye kopyala
      - name: Copy .jar file to VPS
        run: scp -o StrictHostKeyChecking=no build/libs/*.jar ${VPS_USER}@${VPS_IP}:/root/projects/wowdiscordbot/test

      # 12. VPS üzerinde eski container'ı durdur
      - name: Stop existing application on VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${VPS_USER}@${VPS_IP} << 'EOF'
            # Daha önce çalışıyorsa eski süreci sonlandır
            pkill -f 'java -jar' || true
            echo "Eski süreç sonlandırıldı."
          EOF

      # 13. VPS üzerinde uygulamayı başlat
      - name: Run .jar on VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${VPS_USER}@${VPS_IP} << 'EOF'
            # Yeni .jar dosyasını çalıştır
            java -jar /root/projects/wowdiscordbot/test/*.jar &
            echo "Uygulama başarıyla başlatıldı!"
          EOF

      # 14. Başarılı Deployment İle İlgili Mesaj
      - name: Success Message
        run: echo "Deployment başarıyla tamamlandı!"
