name: Deploy to VPS

on:
  push:
    branches:
      - main  # Sadece 'main' dalına yapılan push'larda çalışır.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu Checkout Et
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Mevcut Java sürümlerini temizle
      - name: Clean up existing Java versions
        run: |
          sudo apt-get remove --purge -y openjdk-11-* openjdk-8-* temurin-*
          sudo apt-get autoremove -y

      # 3. Java 17'yi kur
      - name: Install OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      # 4. JAVA_HOME ve PATH değişkenlerini ayarla
      - name: Configure JAVA_HOME and PATH
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      # 5. Sistem PATH'ine Java'yı ekle
      - name: Add Java to PATH
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          echo "JAVA_HOME ve PATH ayarlandı."

      # 6. Java sürümünü doğrula
      - name: Verify Java version
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "PATH: $PATH"
          java -version

      # 7. Gradle wrapper dosyasına çalıştırılabilir izin ver
      - name: Give execute permissions to gradlew
        run: chmod +x ./gradlew

      # 8. Gradle ile build al
      - name: Build with Gradle
        run: ./gradlew clean build

      # 9. SSH Kurulumu
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${VPS_IP} >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking=no" >> ~/.ssh/config

      # 10. .jar dosyasını VPS'ye kopyala
      - name: Copy .jar file to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          scp -o StrictHostKeyChecking=no build/libs/*.jar ${VPS_USER}@${VPS_IP}:/root/projects/wowdiscordbot/test

      # 11. VPS üzerinde eski container'ı durdur
      - name: Stop existing application on VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          echo "VPS_USER: ${VPS_USER}"
          echo "VPS_IP: ${VPS_IP}"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${VPS_USER}@${VPS_IP} << 'EOF'
            pkill -f 'java -jar' || true
            echo "Eski süreç sonlandırıldı."
          EOF

      # 12. VPS üzerinde uygulamayı başlat
      - name: Run .jar on VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${VPS_USER}@${VPS_IP} << 'EOF'
            nohup java -jar /root/projects/wowdiscordbot/test/*.jar > /dev/null 2>&1 &
            echo "Uygulama başarıyla başlatıldı!"
          EOF

      # 13. Başarılı Deployment İle İlgili Mesaj
      - name: Success Message
        run: echo "Deployment başarıyla tamamlandı!"
