name: Deploy to VPS

on:
  push:
    branches:
      - main  # Sadece 'main' dalına yapılan push'larda çalışır.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu Checkout Et
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Mevcut Java sürümlerini temizle
      - name: Clean up existing Java versions
        run: |
          sudo apt-get remove --purge -y openjdk-11-* openjdk-8-* temurin-*
          sudo apt-get autoremove -y

      # 3. Java 17'yi kur
      - name: Install OpenJDK 17
        run: |
          # Java 17'yi yükle
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      # 4. Varsayılan olarak Java 17'yi ayarla
      - name: Set Java 17 as default
        run: |
          # Varsayılan Java 17'yi ayarla
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1711
          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1711
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

      # 5. Java sürümünü doğrula
      - name: Verify Java version
        run: |
          java -version