name: Deploy to VPS

on:
  push:
    branches:
      - main  # Sadece 'main' dalına yapılan push'larda çalışır.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu Checkout Et
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. OpenJDK 17'yi kur
      - name: Install OpenJDK 17
        run: |
          # Önce mevcut Java sürümünü kaldır
          sudo apt-get remove --purge openjdk-11-*
          sudo apt-get remove --purge openjdk-8-*
          
          # OpenJDK 17'yi kur
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          
          # Java sürümünü doğrula
          java -version